#!/bin/bash
#
#SBATCH --job-name=BN_job
#SBATCH --output=BN_log.txt
#
#SBATCH --ntasks=1
#SBATCH --partition=ccs6
#SBATCH --time=72:00:00

srun ./testVNS_DistFlow_Damage "0.2" 50 1.0 0.9 500.0 Rural Experiment/burns-nanuet/ HardenedEnabled Heuristic MCF 0 Output
